blank_issues_enabled: false
contact_links:
  - name: Project README
    url: https://github.com/XFire2025/govlink#readme
    about: Start here for setup, scripts, and docs.
  - name: Questions or help (Discussions)
    url: https://github.com/XFire2025/govlink/discussions
    about: Ask questions and discuss ideas outside of issues.
